trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - 'Setup/SqlScripts/**'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd ./Setup/SqlScripts
    chmod +x ./DatabaseUpdate.sh
    ./DatabaseUpdate.sh $(DB_HOST) $(DB_PASS)
  displayName: 'Run Shell Script'